language: go

go:
  - 1.13.x
  - tip

script:
  - go test -race -coverprofile=coverage.txt -covermode=atomic

after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  email:
    recipients:
      - wnanbei@gmail.com
    on_success: never # default: change
    on_failure: always # default: always