language: go

os:
  - linux
  - osx

go:
  - 1.13.x
  - master

matrix:
  fast_finish: true

script:
  - go test -v -race -coverprofile=coverage.txt -covermode=atomic

after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  email:
    recipients:
      - wnanbei@gmail.com
    on_success: never # default: change
    on_failure: always # default: always