title: Direwolf
description: "Package direwolf is a convient and esay to use http client written in Golang"

author:
  name: "wnanbei"
  url: https://github.com/wnanbei

markdown: kramdown
highlighter: rouge

sidebar_home_link: true

remote_theme: wnanbei/minimal-mistakes

collections:
  zh:
    output: true
    permalink: /:collection/:title/