# Site settings
title: Direwolf
description: "Package direwolf is a convient and esay to use http client written in Golang"

author:
  name: 'wnanbei'
  url: https://github.com/wnanbei

remote_theme: wnanbei/hydeout